### 登录
POST http://{{addr}}/login
Content-Type: application/json

{
    "account": "saltfish",
    "password": "123456"
}

> {% client.global.set("auth_token", response.body.token); %}

### 请求建立websocket连接
GET http://{{addr}}/api/v1/chat
Authorization: Bearer {{auth_token}}
