version: "3"

env:
  MODULE_NAME: github.com/saltfishpr/go-learning

vars:
  VERSION:
    sh: date '+%Y%m%d%H%M%S'

tasks:
  proto:
    cmds:
      - task: proto-go
      - task: proto-js
      - task: proto-java
    silent: true
  proto-go:
    cmds:
      - buf generate --template buf.gen.go.yaml proto
  proto-js:
    cmds:
      - buf generate --template buf.gen.js.yaml buf.build/googleapis/googleapis
      - buf generate --template buf.gen.js.yaml buf.build/envoyproxy/protoc-gen-validate
      - buf generate --template buf.gen.js.yaml buf.build/grpc-ecosystem/grpc-gateway
      - buf generate --template buf.gen.js.yaml proto
  proto-java:
    cmds:
      - buf generate --template buf.gen.java.yaml proto

  build:
    cmds:
      - go build -ldflags "-X main.Version={{.VERSION}}" -o bin/{{.SERVICE_NAME}} {{.MODULE_NAME}}/cmd/{{.SERVICE_NAME}}
    silent: true

  start:
    cmds:
      - bin/{{.SERVICE_NAME}} -conf cmd/{{.SERVICE_NAME}}/configs
    silent: true

  image:
    cmds:
      - docker build --pull --build-arg SERVICE_NAME={{.SERVICE_NAME}} --build-arg VERSION={{.VERSION}} -t {{.DOCKER_HUB_USERNAME}}/{{.SERVICE_NAME}}:{{.VERSION}} -t {{.DOCKER_HUB_USERNAME}}/{{.SERVICE_NAME}}:latest .
    preconditions:
      - test {{.DOCKER_HUB_USERNAME}}
      - test {{.SERVICE_NAME}}
