version: "3"

env:
  MODULE_NAME: github.com/saltfishpr/go-learning

vars:
  VERSION:
    sh: git log -n 1 --format=%h

tasks:
  default:
    cmds:
      - task --list
    silent: true

  proto:
    desc: Generate codes for all language
    cmds:
      - task: proto-go
      - task: proto-js
      - task: proto-java
    silent: true
  proto-go:
    desc: Generate codes for go
    cmds:
      - buf generate --template buf.gen.go.yaml proto
  proto-js:
    desc: Generate codes for js
    cmds:
      - buf generate --template buf.gen.js.yaml proto
  proto-java:
    desc: Generate codes for java
    cmds:
      - buf generate --template buf.gen.java.yaml buf.build/envoyproxy/protoc-gen-validate
      - buf generate --template buf.gen.java.yaml proto

  proto-check:
    desc: Run linting on Protobuf files
    cmds:
      - buf lint proto
    silent: true
  proto-fmt:
    desc: Format Protobuf files
    cmds:
      - buf format -w proto
    silent: true

  build:
    desc: Build service
    preconditions:
      - sh: test {{.SERVICE_NAME}}
        msg: "SERVICE_NAME is required"
    cmds:
      - CGO_ENABLED=0 go build -ldflags "-X main.Version={{.VERSION}}" -o bin/{{.SERVICE_NAME}} {{.MODULE_NAME}}/cmd/{{.SERVICE_NAME}}
    silent: true

  start:
    desc: Start service
    preconditions:
      - sh: test {{.SERVICE_NAME}}
        msg: "SERVICE_NAME is required"
    cmds:
      - bin/{{.SERVICE_NAME}} {{.CLI_ARGS}}
    silent: true

  build-image:
    desc: Build image for all platform
    preconditions:
      - sh: test {{.SERVICE_NAME}}
        msg: "SERVICE_NAME is required"
      - sh: test {{.DOCKER_HUB_USERNAME}}
        msg: "DOCKER_HUB_USERNAME is required"
    cmds:
      - docker buildx build --platform linux/arm,linux/arm64,linux/amd64 --pull --build-arg SERVICE_NAME={{.SERVICE_NAME}} --build-arg VERSION={{.VERSION}} -t {{.DOCKER_HUB_USERNAME}}/{{.SERVICE_NAME}}:{{.VERSION}} -t {{.DOCKER_HUB_USERNAME}}/{{.SERVICE_NAME}}:latest .
