definitions:
  e.ErrorResult:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  fiber.Map:
    additionalProperties: true
    type: object
info:
  contact: {}
paths:
  /register:
    post:
      consumes:
      - application/json
      description: Sign in if account exists. Otherwise, sign up. If success, return
        a jwt token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "201":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResult'
      summary: Sign in or sign up.
      tags:
      - auth
swagger: "2.0"
